version: '3.8'

services:
  flask-app:
    build: .
    container_name: traffic-visualization
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py